### ISSUE TITLE
Failed with error code 182 installation error (@hossamsy)

### ISSUE THREAD

**Issue by chriswayg** [chriswayg/CC-Offline-Package-Generator#1]
### Posted by @hossamsy: 

- I ran OfflinePackageGenerator
- I successfully downloaded the app Install MUSE_2018.1.1-en_AE.app
- I ran the app and it gave me the error message right after I clicked "install": "Failed with error code 182" popped up

OS: macOS High Sierra (10.13) fully updated to date, Python 3.6.0

![A](https://user-images.githubusercontent.com/45803697/86391200-11f1bb00-bca2-11ea-978a-d105fcdb73d8.png)

#### then I used this method:

- Open the Apple Terminal.app
- Copy & paste this command and hit enter:

`/bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/ayyybe/a5f01c6f40020f9a7bc4939beeb2df1d/raw/install.sh)"`

"Then run the Adobe Packager.command in your /Applications folder and follow the on-screen instructions as explained above."

---

- I tried another app Install SPRK_30.2.12-en_AE.app and it worked
- Recreted Install MUSE_2018.1.1-en_AE.app and gave me new error then next time gave me the same 182 error

![Screen Shot 2020-07-02 at 8 41 50 PM](https://user-images.githubusercontent.com/45803697/86392799-b412a280-bca4-11ea-9464-d9ec876f20f5.png)

- Downloaded older version of Muse still same error 182
- It seems the JSON error is from the other apps

> here is the error log, it says some folder does not exist, it seems the package is not complete for this certain application or they changed the folder AMT in new Cloud desktop
> FATAL: Package Zip '/Users/XXXXXXX/Desktop/Adobe Apps June/Install MUSE_2018.1.1-en_AE.app/Contents/Resources/products/./MUSE/AdobeMuse2018.1.1-legal.zip' is not present in ESD Mode
> FATAL: Error occurred in install product workflow with error code 182 error message
> WARN: target folder '/Library/Application Support/Adobe/Adobe Muse CC 2018 AMT/AMT' does not exist, treating package 'AdobeMuse2018.1.1-AMT' as uninstalled
> WARN: target folder '/Applications/Adobe Muse CC 2018' does not exist, treating package 'AdobeMuse2018.1.1-core' as uninstalled
> WARN: target folder '/Applications/Adobe Muse CC 2018/Legal' does not exist, treating package 'AdobeMuse2018.1.1-legal' as uninstalled

> 07/04/20 02:48:31:015 | [WARN] | 3763 | HDSetup | OOBEUtils | CommBridge | | OOBEUtils | 185105 | 0 | pthread_join failed with return code 3
> 07/04/20 02:48:31:015 | [INFO] | 3763 | HDSetup | HDPIM | HDPIMSessionManager | | HDPIM | 185105 | 0 | Inside hdpimTerminateSession
> 07/04/20 02:48:31:016 | [INFO] | 3763 | HDSetup | HDPIM | HDPIMSessionManager | | HDPIM | 185105 | 0 | Exiting hdpimTerminateSession, successfully closed session '0'
> 07/04/20 02:48:31:016 | [INFO] | 3763 | HDSetup | HDSetup | AppContext | | HDSetup | 185105 | 0 |
>  ************************* END Adobe Setup *************************

**Comment by chriswayg** [comment]
### Replies by @ayyybe:

You can find the installer logs in /Library/Logs/Adobe/Installers/Install.log. Please look at and/or post the logs from the most recent installation so we can get more info.

If I had to guess, there is probably another language of the app installed. The tool is really limited right now and will fail in such scenarios, so you'll have to uninstall it and choose a single language.

---

Interesting, there probably needs to be additional parsing for the products xml and/or application json to get whatever is missing. I haven't really touched this project in a while but I might look into it later if I have time.

**Comment by chriswayg** [comment]
I get the same result on Mojave in /Library/Logs/Adobe/Installers/Install.log

```
FATAL: Package Zip '/Users/editor/Desktop/Install MUSE_2018.1.1-en_US.app/Contents/Resources/products/./MUSE/AdobeMuse2018.1.1-legal.zip' is not present in ESD Mode
FATAL: Error occurred in install product workflow with error code 182 error message 
```

Using dummy files will get to this point in the log:

```
 Completed 'DOWNLOAD' task for Package (Name: AdobeMuse2018.1.1-core Version: 2018.1.1.29), Time taken '0' sec 
 Completed 'DOWNLOAD' task for Package (Name: AdobeMuse2018.1.1-en_US Version: 2018.1.1.29), Time taken '0' sec 
```
 
It is looking for two files which are missing:
```
 Completed 'DOWNLOAD' task for Package (Name: AdobeMuse2018.1.1-legal Version: 2018.1.1.29), Time taken '0' sec 
 Completed 'DOWNLOAD' task for Package (Name: AdobeMuse2018.1.1-AMT Version: 2018.1.1.29), Time taken '0' sec 
```

**Comment by inspiredlabs** [comment]
After running the packaged files, I get the message: `Error: TypeError: undefined is not an object (evaluating '$.NSProcessInfo.processInfo') (-2700)`. This happens without `error 182` and prevents the installation package from running at all.

Python and `(-2700)` is mentioned [here](https://gist.github.com/ayyybe/a5f01c6f40020f9a7bc4939beeb2df1d), so it could have been due to the way Python is configured (@2.7 by default), in Big Sur so I reinstalled it from these [instructions](https://stackoverflow.com/questions/47255517/brew-install-python3-didnt-install-pip3), without the group: `sudo chown -R whoami $(brew --prefix)/*`. Yet, it still results in the same error.

This happens for every package, either running the above bash command or `CC_Offline_Package_Generator.app`.

**Comment by ayyybe** [comment]
Installer is messed up in Big Sur, I haven't looked into it at all but you can bypass it completely for now by running `sudo "/Library/Application Support/ Adobe/Adobe Desktop Common/HDBox/Setup" --install=1 --driverXML="/path/to/Install XXXX_1.2.3-en_US.app/Contents/Resources/products/driver.xml"` in terminal

**Comment by inspiredlabs** [comment]
Thanks. After looked at your command, it returns `Exit Code: 103`, so I went straight to the log. It read: `Please check the path is valid and correct permissions are applied.`, so I tinkered with the path again. Then it returned `Exit Code: 103` again, but the log gave me some clues:

```
FATAL: No valid mode has been specified. Please refer documentation for more help.
ERROR: The argument does not contain any "="
ERROR: The "--" is not there for the argument. Every argument should have "--"
```

Turns out `-- install=1`, isn't valid. But this works:

 `sudo "/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Setup" --install=1 --driverXML=/Users/<USERNAME>/Downloads/Install\ XXXX_0.0.0-xx_XX.app/Contents/Resources/products/driver.xml`

Seems like there's a log going on behind `Exit Code: 103`! Thanks again.

**Comment by ayyybe** [comment]
> Turns out `-- install=1`, isn't valid. But this works:
> `--install=1`

My bad, typo

**Comment by inspiredlabs** [comment]
Speed Grade 9.0 & 6.0 borked: `Exit Code: 103`, although all other tests worked with `Exit Code: 0`, returning: `nil host used in call to allowsAnyHTTPSCertificateForHost`.

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which has been tested to run stable from High Sierra to Monterey and has resolved the issues reported here. This new version packages the updated script [adobe-packager](https://github.com/Drovosek01/adobe-packager) _(version 0.1.4)_ by Drovosek01 which can be found in the `src/` folder. 

Download the updated app: [CC Offline Package Generator ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)
