### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Tb3986** [chriswayg/CC-Offline-Package-Generator#2]
Hello,
i'm trying to download some product but i get this error:

[PHSP_21.2.3] Downloading application.json
Traceback (most recent call last):
  File "ccdl.py", line 387, in <module>
  File "ccdl.py", line 236, in get_application_json
  File "json/__init__.py", line 348, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[1782] Failed to execute script ccdl
administrator@Mac-di-Administrator ~ % 

Any solution?

Thanks

**Comment by yozhic** [comment]
Yes, exactly same errors here:
```sh
[PHSP_21.2.3] Downloading application.json
Traceback (most recent call last):
  File "/Applications/Adobe Creative Cloud/ccdl.py", line 364, in <module>
    app_json = get_application_json(s, v)
  File "/Applications/Adobe Creative Cloud/ccdl.py", line 221, in get_application_json
    return json.loads(r(ADOBE_APPLICATION_JSON_URL.format(name=sapCode, version=version, platform='osx10')))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[Process completed]
```
**ayyybe**, we are waiting for your fix ))

**Comment by jane-remover** [comment]
Getting the same issue:

```
Creating Install PHSP_21.2.3-en_US.app

Preparing...

[PHSP_21.2.3] Downloading application.json
Traceback (most recent call last):
  File "ccdl.py", line 387, in <module>
  File "ccdl.py", line 236, in get_application_json
  File "json/__init__.py", line 348, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[83740] Failed to execute script ccdl
```

**Comment by Mrc527** [comment]
Same here, any news?

**Comment by clairekardas** [comment]
I got it working by executing the following command in the terminal

`/bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/ayyybe/a5f01c6f40020f9a7bc4939beeb2df1d/raw/install.sh)"
`

This downloads the Adobe macOS Package Generator 0.1.2-hotfix1 by @ayyybe. Then run Adobe Packager.command from /Applications. FYI this also works for Adobe CC 2021 products!
<img width="682" alt="Screenshot 2020-10-26 at 08 37 32" src="https://user-images.githubusercontent.com/15703840/97145529-a1960a80-1766-11eb-999a-7e3919c8c756.png">

After the download finishes, you‘l have something along the lines of Install PHSP_22.0-en_US in your desired download folder.
Open that .app file and you'll see that it downloaded just fine.

The product(s) will install.

<img width="1440" alt="Screenshot 2020-10-26 at 08 55 29" src="https://user-images.githubusercontent.com/15703840/97146972-0e120900-1769-11eb-8bf2-fc38882431ec.png">

**Comment by Tb3986** [comment]
> I got it working by executing the following command in the terminal
> 
> `/bin/bash -c "$(curl -fsSL https://gist.githubusercontent.com/ayyybe/a5f01c6f40020f9a7bc4939beeb2df1d/raw/install.sh)" `
> 
> This downloads the Adobe macOS Package Generator 0.1.2-hotfix1 by @ayyybe. Then run Adobe Packager.command from /Applications. FYI this also works for Adobe CC 2021 products!
> <img alt="Screenshot 2020-10-26 at 08 37 32" width="682" src="https://user-images.githubusercontent.com/15703840/97145529-a1960a80-1766-11eb-999a-7e3919c8c756.png">
> 
> After the download finishes, you‘l have something along the lines of Install PHSP_22.0-en_US in your desired download folder.
> Open that .app file and you'll see that it downloaded just fine.
> 
> The product(s) will install.
> 
> <img alt="Screenshot 2020-10-26 at 08 55 29" width="1440" src="https://user-images.githubusercontent.com/15703840/97146972-0e120900-1769-11eb-8bf2-fc38882431ec.png">

Thanks but i have a problem trying to install python3 for this command. I get a stupid error as usual. Stupid mac.

**Comment by clairekardas** [comment]
@Tb3986 If you share the python3 installation error message with me I might be able to look into this 🙂

**Comment by Tb3986** [comment]
> @Tb3986 If you share the python3 installation error message with me I might be able to look into this 🙂

https://i.postimg.cc/2S6KbwYM/Untitled.png

Says: is not available in the server bla bla bla bla

**Comment by Tb3986** [comment]
Nevermind, solved, thanks though.

**Comment by blackmailswitch** [comment]
helo to all and to developer
i have exactly same errors from first post
with https://gist.githubusercontent.com/ayyybe/a5f01c6f40020f9a7bc4939beeb2df1d/raw/install.sh im unable to download some older versions...
how its possible to be solved errors?

High Sierra 17G14042 Python 3 installed
Regards
Mike

**Comment by clairekardas** [comment]
Hi @blackmailswitch! 
Could you post the exact output of the error message that Adobe Packager.command is giving you when trying to download older versions? Without it we can’t see what the issue is exactly.

**Comment by blackmailswitch** [comment]
Hi @clairekardas that was fast) thanks

=================================
= Adobe macOS Package Generator =
========= 0.1.2-hotfix1 =========

Downloading products.xml

Parsing products.xml
CDN: https://ccmdls.adobe.com
27 products found:

[AEFT] After Effects
[AEFTBETA] After Effects (Beta)
[AERO] Aero (Beta)
[AICY] InCopy
[AME] Media Encoder
[AMEBETA] Media Encoder (Beta)
[AUDT] Audition
[AUDTBETA] Audition (Beta)
[CHAR] Character Animator
[CHARBETA] Character Animator (Beta)
[DRWV] Dreamweaver
[ESHR] Dimension
[FLPR] Animate
[IDSN] InDesign
[ILST] Illustrator
[KBRG] Bridge
[LRCC] Lightroom
[LTRM] Lightroom Classic
[MUSE] Muse CC
[PHSP] Photoshop
[PPRO] Premiere Pro
[PPROBETA] Premiere Pro (Beta)
[PRLD] Prelude
[RUSH] Premiere Rush
[RUSHBETA] Premiere Rush (Beta)
[SPRK] XD
[UXPD] UXP Developer Tools

Please enter the SAP Code of the desired product (eg. PHSP for Photoshop): AEFT

After Effects 17.7
After Effects 18.0

Please enter the desired version (eg. 21.2.3): 


im unable to download anything older..

with new one

====================================
=== CC Offline Package Generator ===
============== 0.1.2.2 =============

More info: https://github.com/chriswayg/CC-Offline-Package-Generator
           https://gist.github.com/ayyybe/a5f01c6f40020f9a7bc4939beeb2df1d

Downloading products.xml

Parsing products.xml
CDN: https://ccmdls.adobe.com
30 products found:

[AEFT] After Effects
[AEFTBETA] After Effects (Beta)
[AERO] Aero (Beta)
[AICY] InCopy
[AME] Media Encoder
[AMEBETA] Media Encoder (Beta)
[ANMLBETA] Character Animator CC (Beta)
[AUDT] Audition
[AUDTBETA] Audition (Beta)
[CHAR] Character Animator
[CHARBETA] Character Animator (Beta)
[DRWV] Dreamweaver
[ESHR] Dimension
[FLPR] Animate
[FUSE] Fuse CC (Beta)
[IDSN] InDesign
[ILST] Illustrator
[KBRG] Bridge
[LRCC] Lightroom
[LTRM] Lightroom Classic
[MUSE] Muse CC
[PHSP] Photoshop
[PPRO] Premiere Pro
[PPROBETA] Premiere Pro (Beta)
[PRLD] Prelude
[RUSH] Premiere Rush
[RUSHBETA] Premiere Rush (Beta)
[SPGD] SpeedGrade CC (2015)
[SPRK] XD
[UXPD] UXP Developer Tools

Please enter the SAP Code of the desired product (eg. PHSP for Photoshop): AEFT

After Effects 11.0
After Effects 12.0
After Effects 13.0
After Effects 13.5
After Effects 13.8.0
After Effects 13.8.1
After Effects 14.0.0
After Effects 14.0.1
After Effects 14.1.0
After Effects 14.2.0
After Effects 14.2.1
After Effects 14.2.2
After Effects 15.0.0
After Effects 15.0.1
After Effects 15.1
After Effects 15.1.1
After Effects 15.1.2
After Effects 16.0
After Effects 16.0.1
After Effects 16.1
After Effects 16.1.1
After Effects 16.1.2
After Effects 16.1.3
After Effects 17.0
After Effects 17.0.1
After Effects 17.0.2
After Effects 17.0.4
After Effects 17.0.5
After Effects 17.0.6
After Effects 17.1
After Effects 17.1.1
After Effects 17.1.2
After Effects 17.1.3
After Effects 17.1.4
After Effects 17.5
After Effects 17.5.1
After Effects 17.6
After Effects 17.7
After Effects 18.0

Please enter the desired version (eg. 21.0.3): 


but.. 

Please enter the desired version (eg. 21.0.3): 17.6

Available languages: en_US, en_GB, en_IL, en_AE, es_ES, es_MX, pt_BR, fr_FR, fr_CA, fr_MA, it_IT, de_DE, nl_NL, ru_RU, uk_UA, zh_TW, zh_CN, ja_JP, ko_KR, pl_PL, hu_HU, cs_CZ, tr_TR, sv_SE, nb_NO, fi_FI, da_DK

Please enter the desired install language, or nothing for [en_US]: 

Please navigate to the desired downloads folder, or cancel to abort.

sapCode: AEFT
version: 17.6
installLanguage: en_US
dest: /Users/mike/Desktop/Install AEFT_17.6-en_US.app

Creating Install AEFT_17.6-en_US.app

Preparing...

[AEFT_17.6] Downloading application.json
Traceback (most recent call last):
  File "ccdl.py", line 387, in <module>
  File "ccdl.py", line 236, in get_application_json
  File "json/__init__.py", line 348, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[1245] Failed to execute script ccdl

thanks
Mike

**Comment by blackmailswitch** [comment]
hi @clairekardas 
tried to change
from -
ADOBE_PRODUCTS_XML_URL = 'https://cdn-ffc.oobesaas.adobe.com/core/v5/products/all?_type=xml&channel=ccm,sti&platform=osx10,osx10-64&productType=Desktop'
ADOBE_APPLICATION_JSON_URL = 'https://cdn-ffc.oobesaas.adobe.com/core/v3/applications'

to - 
ADOBE_PRODUCTS_XML_URL = 'https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm&platform=osx10-64&productType=Desktop'
ADOBE_APPLICATION_JSON_URL = 'https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v2/applications?name={name}&version={version}&platform={platform}'


i have full application list, old and new ones
but, unable to download

=================================
= Adobe macOS Package Generator =
========= 0.1.2-hotfix1 =========

Downloading products.xml

Parsing products.xml
CDN: https://ccmdls.adobe.com
30 products found:

[AEFT] After Effects
[AEFTBETA] After Effects (Beta)
[AERO] Aero (Beta)
[AICY] InCopy
[AME] Media Encoder
[AMEBETA] Media Encoder (Beta)
[ANMLBETA] Character Animator CC (Beta)
[AUDT] Audition
[AUDTBETA] Audition (Beta)
[CHAR] Character Animator
[CHARBETA] Character Animator (Beta)
[DRWV] Dreamweaver
[ESHR] Dimension
[FLPR] Animate
[FUSE] Fuse CC (Beta)
[IDSN] InDesign
[ILST] Illustrator
[KBRG] Bridge
[LRCC] Lightroom
[LTRM] Lightroom Classic
[MUSE] Muse CC
[PHSP] Photoshop
[PPRO] Premiere Pro
[PPROBETA] Premiere Pro (Beta)
[PRLD] Prelude
[RUSH] Premiere Rush
[RUSHBETA] Premiere Rush (Beta)
[SPGD] SpeedGrade CC (2015)
[SPRK] XD
[UXPD] UXP Developer Tools

Please enter the SAP Code of the desired product (eg. PHSP for Photoshop): AEFT

After Effects 11.0
After Effects 12.0
After Effects 13.0
After Effects 13.5
After Effects 13.8.0
After Effects 13.8.1
After Effects 14.0.0
After Effects 14.0.1
After Effects 14.1.0
After Effects 14.2.0
After Effects 14.2.1
After Effects 14.2.2
After Effects 15.0.0
After Effects 15.0.1
After Effects 15.1
After Effects 15.1.1
After Effects 15.1.2
After Effects 16.0
After Effects 16.0.1
After Effects 16.1
After Effects 16.1.1
After Effects 16.1.2
After Effects 16.1.3
After Effects 17.0
After Effects 17.0.1
After Effects 17.0.2
After Effects 17.0.4
After Effects 17.0.5
After Effects 17.0.6
After Effects 17.1
After Effects 17.1.1
After Effects 17.1.2
After Effects 17.1.3
After Effects 17.1.4
After Effects 17.5
After Effects 17.5.1
After Effects 17.6
After Effects 17.7
After Effects 18.0

Please enter the desired version (eg. 21.2.3): 17.6

Available languages: en_US, en_GB, en_IL, en_AE, es_ES, es_MX, pt_BR, fr_FR, fr_CA, fr_MA, it_IT, de_DE, nl_NL, ru_RU, uk_UA, zh_TW, zh_CN, ja_JP, ko_KR, pl_PL, hu_HU, cs_CZ, tr_TR, sv_SE, nb_NO, fi_FI, da_DK

Please enter the desired install language, or nothing for [en_US]: 

Please navigate to the desired downloads folder, or cancel to abort.

sapCode: AEFT
version: 17.6
installLanguage: en_US
dest: /Users/mike/Desktop/AEFT/Install AEFT_17.6-en_US.app
Traceback (most recent call last):
  File "/dev/fd/63", line 380, in <module>
  File "/dev/fd/63", line 380, in <listcomp>
KeyError: 'ACR'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Proces finalizat]

Thanks
Mike

**Comment by blackmailswitch** [comment]
hello @clairekardas 
anyway, after I installed Homebrew (/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)") and next after TQDM (pip3 install tqdm)

still///
====================================
=== CC Offline Package Generator ===
============== 0.1.2.2 =============
sapCode: AEFT
version: 17.6
installLanguage: en_US
dest: /Users/mike/Desktop/Install AEFT_17.6-en_US.app

Creating Install AEFT_17.6-en_US.app

Preparing...

[AEFT_17.6] Downloading application.json
Traceback (most recent call last):
  File "/dev/fd/63", line 387, in <module>
  File "/dev/fd/63", line 236, in get_application_json
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

Thanks
Mike

**Comment by blackmailswitch** [comment]
hello @clairekardas 
i fixed, used as base old code
https://github.com/blackmailswitch/CC-Offline-Package-Generator/blob/e5fd25b409420d2e9aa91e50ba8ac49fec0b2da5/src/ccdl.py

Thanks
Mike

**Comment by Tb3986** [comment]
> hi @clairekardas
> tried to change
> from -
> ADOBE_PRODUCTS_XML_URL = 'https://cdn-ffc.oobesaas.adobe.com/core/v5/products/all?_type=xml&channel=ccm,sti&platform=osx10,osx10-64&productType=Desktop'
> ADOBE_APPLICATION_JSON_URL = 'https://cdn-ffc.oobesaas.adobe.com/core/v3/applications'
> 
> to -
**> ADOBE_PRODUCTS_XML_URL = 'https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v4/products/all?_type=xml&channel=ccm&platform=osx10-64&productType=Desktop'
> ADOBE_APPLICATION_JSON_URL = '[https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v2/applications?name={name}&version={version}&platform={platform}](https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v2/applications?name=%7Bname%7D&version=%7Bversion%7D&platform=%7Bplatform%7D)'**

You say to replace with the new string but exactly where? I don't get this part.

**Comment by blackmailswitch** [comment]
@Tb3986 
Hello, check attached link from previous post

**Comment by Tb3986** [comment]
> @Tb3986
> Hello, check attached link from previous post

i did but i don't know where do i have to copy this "ccdl.py."

**Comment by blackmailswitch** [comment]
Well, you just run it from terminal

joi, 15 apr. 2021, 20:26 Tb3986 ***@***.***> a scris:

**Comment by m0mft** [comment]
Hello 
I got through all the things  but at the end I got this error and I have no idea what should I do please help

sapCode: PHSP
version: 22.4.3
installLanguage: en_US
dest: /Applications/Install PHSP_22.4.3-en_US.app
Traceback (most recent call last):
  File "/dev/fd/63", line 379, in <module>
  File "/dev/fd/63", line 379, in <listcomp>
KeyError: '2.2.1'
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

Please somebody help me!!!!!!

<img width="1440" alt="Screen Shot 2021-08-11 at 2 42 48 AM" src="https://user-images.githubusercontent.com/88748851/128941758-160c7346-0521-4a3c-8198-b99474eba268.png">

**Comment by clairekardas** [comment]
Hi @fathi-mohmmadm and everyone else!
Adobe Offline Package Generator v0.1.2 by @ayyybe is no longer being updated.
@thpryrchn created a new gist and updated it to v0.1.4. This new version works as of right now and also added M1 support.
You can find it here: https://gist.github.com/thpryrchn/c0ea1b6793117b00494af5f05959d526

To update your Adobe Packager.command just run

`/bin/bash -c "$(curl -fsSL https://gist.github.com/thpryrchn/c0ea1b6793117b00494af5f05959d526/raw/install.sh)"`

from the terminal. Hopw this helps!

**Comment by thpryrchn** [comment]
Or you can get it from the Github here: https://github.com/Drovosek01/adobe-packager

I update the Gist as well to match, but it is easier to start issues on the Github that @Drovosek01 made for the project. He made me a contributor so I can maintain that github :)

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which packages the updated script _(version 0.1.4)_ by [Drovosek01](https://github.com/Drovosek01) / [adobe-packager](https://github.com/Drovosek01/adobe-packager), which can be found in the `src/` folder.

Download: [CC Offline Package Generator 0.1.4_1 ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which has been tested to run stable from High Sierra to Monterey and has resolved the issues reported here. This new version packages the updated script [adobe-packager](https://github.com/Drovosek01/adobe-packager) _(version 0.1.4)_ by Drovosek01 which can be found in the `src/` folder. 

Download the updated app: [CC Offline Package Generator ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)
