### ISSUE TITLE
Not work now

### ISSUE THREAD

**Issue by wention** [chriswayg/CC-Offline-Package-Generator#3]
Downloading application.json failed with 400

**Comment by wention** [comment]
https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v2/applications?name=PHSP&version=22.0.1&platform=osx10-64
Request error on link

**Comment by chriswayg** [comment]
not clear which application download failed

Please resubmit bug report, if still relevant.

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which has been tested to run stable from High Sierra to Monterey and has resolved the issues reported here. This new version packages the updated script [adobe-packager](https://github.com/Drovosek01/adobe-packager) _(version 0.1.4)_ by Drovosek01 which can be found in the `src/` folder. 

Download the updated app: [CC Offline Package Generator ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)
