### ISSUE TITLE
Icns file location needs updating

### ISSUE THREAD

**Issue by inspiredearth** [chriswayg/CC-Offline-Package-Generator#4]
Hi there. 

Thanks for packaging this into a DMG.

Just wanted to let you know line 374 in `ccdl.py` needs update.

It's currently:

 `icon_path = '/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Install.app/Contents/Resources/app.icns'`

And needs to be:

`    icon_path = '/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Install.app/Contents/Resources/CreativeCloudInstaller.icns'`

**Comment by Adamsapplespie** [comment]
If you navigate to that Resources folder and change the name manually, it works.

**Comment by chriswayg** [comment]
> needs to be:
> ` icon_path = '/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Install.app/Contents/Resources/CreativeCloudInstaller.icns'`

@inspiredearth thank you for the fix. The ccdl.py script works now when testing it directly from the CC Offline Package Generator.command for testing

I still need to repackage it into the dmg and will upload a new package once finished.

**Comment by inspiredearth** [comment]
Thanks. I am aware of how to edit it myself, and make it work. I raised the 
issue because I believe it would be best if the source code is edited so 
that it works for everyone else who tries to use this script.
👍

**Comment by inspiredearth** [comment]
@chriswayg

Great. Thanks for the prompt attention to this. I'm sure the less code 
savvy among your users will be glad. And thank you for putting all this 
into a dmg to begin with. Much appreciated.

**Comment by inspiredearth** [comment]
@chriswayg -- I see this bug still exists in the most recent script you've released. Here's a reminder to make the code change. Cheers ...

**Comment by goyafog65** [comment]
I changed the file name and I got a new ERROR

[PHSP_22.4.3] Downloading application.json
Traceback (most recent call last):
  File "ccdl.py", line 387, in <module>
  File "ccdl.py", line 236, in get_application_json
  File "json/__init__.py", line 348, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[54929] Failed to execute script ccdl

Can this be solved?

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which packages the updated script _(version 0.1.4)_ by [Drovosek01](https://github.com/Drovosek01) / [adobe-packager](https://github.com/Drovosek01/adobe-packager), which can be found in the `src/` folder.

Download: [CC Offline Package Generator 0.1.4_1 ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which has been tested to run stable from High Sierra to Monterey and has resolved the issues reported here. This new version packages the updated script [adobe-packager](https://github.com/Drovosek01/adobe-packager) _(version 0.1.4)_ by Drovosek01 which can be found in the `src/` folder. 

Download the updated app: [CC Offline Package Generator ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)
