### ISSUE TITLE
Can't download latest Adobe CC 2021 - June update

### ISSUE THREAD

**Issue by Matgen84** [chriswayg/CC-Offline-Package-Generator#7]
Hi

I can't download latest Indesign 16.3.1 and Illustrator 25.3.1: there aren't in the list

*******
Imac13,2 - macOS Catalina 10.15.7 (19H1217)

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which packages the updated script _(version 0.1.4)_ by [Drovosek01](https://github.com/Drovosek01) / [adobe-packager](https://github.com/Drovosek01/adobe-packager), which can be found in the `src/` folder.

Download: [CC Offline Package Generator 0.1.4_1 ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which has been tested to run stable from High Sierra to Monterey and has resolved the issues reported here. This new version packages the updated script [adobe-packager](https://github.com/Drovosek01/adobe-packager) _(version 0.1.4)_ by Drovosek01 which can be found in the `src/` folder. 

Download the updated app: [CC Offline Package Generator ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)
