### ISSUE TITLE
Error in ccdl.py and ElementTree.py

### ISSUE THREAD

**Issue by Drovosek01** [chriswayg/CC-Offline-Package-Generator#8]
After starting the program, I get this error.
Mac M1 Big Sur 11.4

![Снимок экрана 2021-07-24 в 12 00 53](https://user-images.githubusercontent.com/29478700/126865160-52556dd6-6ed4-47cf-a758-ec373597035f.png)

I have XCode components installed.
Why does this error appear and how can I fix it?

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which packages the updated script _(version 0.1.4)_ by [Drovosek01](https://github.com/Drovosek01) / [adobe-packager](https://github.com/Drovosek01/adobe-packager), which can be found in the `src/` folder.

Download: [CC Offline Package Generator 0.1.4_1 ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which has been tested to run stable from High Sierra to Monterey and has resolved the issues reported here. This new version packages the updated script [adobe-packager](https://github.com/Drovosek01/adobe-packager) _(version 0.1.4)_ by Drovosek01 which can be found in the `src/` folder. 

Download the updated app: [CC Offline Package Generator ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)
