### ISSUE TITLE
FYI — v0.1.2 is broken. USE THIS VERSION INSTEAD

### ISSUE THREAD

**Issue by inspiredearth** [chriswayg/CC-Offline-Package-Generator#9]
This is just a friendly FYI to all those facing the failure of v0.1.2 of this script. I think it is fair to say Chriswayg is no longer maintaining it. 

There is an updated version available [here](https://gist.github.com/thpryrchn/c0ea1b6793117b00494af5f05959d526).

It is not packaged like Chris's version. So the easiest way to obtain and run it is to use the following command (in Terminal).

```
/bin/bash -c "$(curl -fsSL https://gist.github.com/thpryrchn/c0ea1b6793117b00494af5f05959d526/raw/install.sh)"

— THEN — 

open "/Applications/Adobe Packager.command"
```
The above script will create the `/Applications/Adobe Packager.command` file. You are then running that. And voila.

It works perfectly (as of 20210831)

**Comment by chriswayg** [comment]
I appreciate your feedback and issue report for _CC Offline Package Generator_.

I have released a new version which has been tested to run stable from High Sierra to Monterey and has resolved the issues reported here. This new version packages the updated script [adobe-packager](https://github.com/Drovosek01/adobe-packager) _(version 0.1.4)_ by Drovosek01 which can be found in the `src/` folder. 

Download the updated app: [CC Offline Package Generator ](https://github.com/chriswayg/CC-Offline-Package-Generator/releases/latest)

**Comment by inspiredearth** [comment]
Thanks Chris. Glad to see this revived. Have yet to test it, so no feedback on that side of things. If I run into issues, I'll open a new ticket to let you know. 
All the best ... J
